### PR TITLE
Version 5/gulpfile dir support

### PR DESCRIPTION
**Pull request by dkebler**
Nick,

Added hide panel command, added main menu items and new side bar menu items (see new readme).  Extensive rewrite of readme file with new features and clarification of old ones.

Hope you like it :-).  Readme is heavily edited so even if you like it you should read it carefully for clarity, errors and typos. I did check all the links and anchors.

I thought adding a hide panel command would be nice as that's the first thing I wanted to be able to do and it compliments the show panel command.  Unfortunately I can't get anyone at superuser to help me figure out how to turn it into a toggle menu item.

I pulled your latest before making the PR so looks like it is ok to merge with your branch.

Cheers!

PS
Had a thought about an improved list plugins command but will make that a new enhancement issue.

### CODE REVIEW

**Comment by NicoSantangelo** [comment]
Awesome!
I'll check to see if there's any way to know if the panel is open to make a toggle later, but just a question, instead of running `Gulp: Hide panel`, you could just press `Esc`, right? or there's a use case I'm not seeing?.

I'm re-reading the README and trying out the menu before merging. I'll let you know if there's any issue, thanks a lot for the PR!

**Comment by dkebler** [comment]
Already noticed a couple typos :-).

never new esc was used like that :-).
I just saw your code already had such a fucntion so just enabled it.

I say leave it in for unknowing folks like me but might as well mention
esct in the readme.

I'm fixing few typos and adding that note.  Look for new commit.

On Wed, Aug 19, 2015 at 5:29 PM, Nicolás Santángelo <
notifications@github.com> wrote:

> Awesome!
> I'll check to see if there's any way to know if the panel is open to make
> a toggle later, but just a question, instead of running Gulp: Hide panel,
> you could just press Esc, right? or there's a use case I'm not seeing?.
>
> I'm re-reading the README and trying out the menu before merging. I'll let
> you know if there's any issue, thanks a lot for the PR!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NicoSantangelo/sublime-gulp/pull/45#issuecomment-132836211>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by NicoSantangelo** [comment]
I like this a lot!
I didn't find typos but I'll give it another read before merging with master.

I'm going to merge this PR, make a few additions (listed below) and release this!

Todo:

1. When using `Gulp: Hide panel` check if `results_in_new_tab` is `true` and see if I can close the tab or just do nothing (right now is failing)
2. Check if I can add the current selected path on the sidebar (if the user has more than one project with a `gulpfile.js` file, the package won't prompt the selection)

And, this last two if you think is better:

1. Change `Run Default Task` for `Run Arbitrary Task` when this last one is ready
2. Add your Github handle to Acknowledgments :)

Thanks again and let me know

**Comment by dkebler** [comment]
1. Yes I was wondering how gulp_hide_panel would work with tabs and did not
test that.  It may be an issue?
2. I've never opened two projects in the same window(instance) at the same
time so at least for me this is a non-issue.  Is this common usage?

1. When one types just "gulp" at the terminal it runs whatever tasks is
named "default" if it exists so I was just trying to provide the same
simplicity built in to Gulp itself.  Typically folks make their development
build their 'default' since it's the one that gets called over and over.
Like my setup.    gulp.task('default', ['build:development']);
2.  Acknowledgement is appreciated.

On Thu, Aug 20, 2015 at 10:53 AM, Nicolás Santángelo <
notifications@github.com> wrote:

> I like this a lot!
> I didn't find typos but I'll give it another read before merging with
> master.
>
> I'm going to merge this PR, make a few additions (listed below) and
> release this!
>
> Todo:
>
>    1. When using Gulp: Hide panel check if results_in_new_tab is true and
>    see if I can close the tab or just do nothing (right now is failing)
>    2. Check if I can add the current selected path on the sidebar (if the
>    user has more than one project with a gulpfile.js file, the package
>    won't prompt the selection)
>
> And, this last two if you think is better:
>
>    1. Change Run Default Task for Run Arbitrary Task when this last one
>    is ready
>    2. Add your Github handle to Acknowledgments :)
>
> Thanks again and let me know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NicoSantangelo/sublime-gulp/pull/45#issuecomment-133097634>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by NicoSantangelo** [comment]
1. It wont be an issue, just a minor tweak! :)
2. I'm not really sure how common it is, if it gets too cumbersome I'll leave it for later

-

1. Oh I get it. Ok, when I'm done with the arbitrary tasks I'll see if adding a new option to the menu doesn't create too much clutter but I'll leave `Run Default Task`

**Comment by NicoSantangelo** [comment]
Merged!
I'll create the release as soon as I can, thanks a lot for the help.

**Pull request merged**
