### PR TITLE
Added feature "Task On Save". - 

### PR DESCRIPTION
**Pull request by rhaldkhein**
Auto run a task when a file is saved. Task can also vary base on file types (just specify in settings file).

Additional settings example.
"task_on_save": {
   "webpack": ".js",
   "stylus": ".styl",
   "other_task": [".ext1", ".ext2"]
}

This settings can also be set per project.

### CODE REVIEW

**Comment by NicoSantangelo** [comment]
Awesome!

Let me give it a try tonight before merging it.

**Comment by rhaldkhein** [comment]
Thanks.

Made this because I (maybe someone else) always forgot to run watch command for file changes. :)

**Comment by NicoSantangelo** [comment]
Just tested it and it works great, thanks a lot!

A few minor things:
- I think `tasks_on_save` it's a better name (picky I know), because the user can define as many as he or she wants. What do you think?
- Could you please right a mini example on `Gulp.settings` ? like the one for `flags`
- Could you please add a small explanation of how the setting is used to the README ? It does not have to be complicated but at least to explain what the `key` and `value` mean, and that the value can be an array

That's all!

**Comment by rhaldkhein** [comment]
Sure!

But before that, there's one issue. Tasks for specific extension (like .js file) will run on all files in project, but what if we have files that should not be affected with. Like following example diagram.

./app/view/template.js ---> (should run template compile task)
./app/controller/index.js ---> (should run webpack or browserify task)
./gulpfile.js ---> (should not run any task)

To solve this issue, regex or glob should be used. Instead of just file extension.

**Comment by rhaldkhein** [comment]
Hi Nico, Updated. Let me know if you need anything else. Thanks.

**Comment by NicoSantangelo** [comment]
Perfect! 

Thanks a lot for this I'll add it to the next release, this weekend

**Pull request merged**
